server:
  port: 9003
spring:
  application:
    name: order

dubbo:
  registry:
#    address: nacos://192.168.0.21:8888
    address: nacos://192.168.0.9:8848
    username: nacos
    password: nacos
  application:
    name: order