#指定Eureka服务器
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka

#指定具体服务的负载均衡策略
search01:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#指定服务名称
spring:
  application:
    name: client01

#指定服务端口
server:
  port: 8090
